# Words that aren't allowed
# to be typed in chat
#
# This check is designed to see
# if the message contains the
# anti-curse, and it also has
# additional checks for bypassing
# using symbols or spaces
#
# Disable by AntiCurse: []
AntiCurse: []

# This is if you want the
# word "ass" to be checked for in chat
#
# This exists for a more efficient
# check, because ass is slightly more
# annoying due to words like "grass" and "class"
AssCheck: true

# Maximum caps in a message
# Disable by MaxCaps: 0
MaxCaps: 20

# Cooldown in-between chat messages
# Disable by ChatCooldown: 0
ChatCooldown: 2

# List of commands to have a cooldown
# Cooldowns do NOT store in a database
# therefore I do NOT recommend using this
# for serious cooldown usages like kits
#
# Disable by CommandCooldowns: []
CommandCooldowns:
  - msg:2
  - message:2
  - tell:2
  - whisper:2
  - pay:10

# Simple chat formatting
# has PlaceholderAPI support
# message is placed after string
#
# Disable by ChatFormat: ""
ChatFormat: "&r%player% &8&l> &f"

# Should the plugin function
# as a global chat through
# the proton library
GlobalChat: false

# Disable any of the below by -> ""
AntiCurseMessage: "&cWarning: Your message contains a bad word!"
MaxCapsMessage: "&cWarning: Too many caps!"
ChatCooldownMessage: "&cError: You can't type for another %time%!"
CommandCooldownMessage: "&cError: You can't type '%command%' for another %time%!"
ReloadMessage: "&aChatHelper config successfully reloaded!"
